#异常

PHP中的异常语法和其他语言的异常基本相同。

语法示例：

```
class SubException1 extends Exception{

}

class SubException2 extends Exception{

}

try{
	throw new SubException2("an subexception2 happen.\n");
}catch (SubException1 $e){
	echo $e->getMessage();
}catch (SubException2 $e){
	echo $e->getMessage();
}finally{
	echo "do something whether exception heppen or not.\n";
}

/*output:
an subexception2 happen.
do something whether exception heppen or not.
*/
```

注意：

- 所有异常类必须是内置类`Exception`或其子类，否则会报Fatal Error。
- finally子句是无论是否发生异常都会被执行的语句，可用来做一些资源释放的事儿。
- 多个catch也是按顺序对异常对象的类进行匹配的，最先被匹配的会被执行，子类异常可以被匹配为父类的异常。
- catch子句中可以重新抛出异常。
- 如果异常对象没有被捕获，PHP会报Fatal Error，并且输出"Uncaught Exception ..."的信息。但如果使用set_exception_handler()设置了一个异常处理函数，则该处理函数会被执行，执行之后终止脚本。注意，这种情况下，如果有finally子句，它会先被执行，再执行异常处理函数，最后再终止脚本。

PHP内置的函数主要使用错误报告的方式处理错误，只有较现代的面向对象的PHP扩展使用异常来处理错误。

##Exception类

一个异常对象最重要的功能是表明异常类型、记载异常发生的位置、记录异常信息。

异常类型通过异常对象所属的类体现。而记载异常发生的位置和记录异常信息则可由Exception类实现的属性和方法得到。Exception类的原型如下：

```
Exception {
	/* 属性 */
	protected string $message ;
	protected int $code ;
	protected string $file ;
	protected int $line ;
	/* 方法 */
	public __construct ([ string $message = "" [, int $code = 0 [, Exception $previous = NULL ]]] )
	final public string getMessage ( void )
	final public Exception getPrevious ( void )
	final public int getCode ( void )
	final public string getFile ( void )
	final public int getLine ( void )
	final public array getTrace ( void )
	final public string getTraceAsString ( void )
	public string __toString ( void )
	final private void __clone ( void )
}
```
构造函数的3个参数分别是异常信息、异常代码和前一个异常（用在连续抛出异常的场景）。

getMessage、getCode、getPrevious、getFile、getLine、getTraceAsString(getTrace)这几个函数分别用以获取异常信息、异常代码、前一个异常、异常被抛出的文件、异常被抛出的行数、异常被抛出时的函数调用栈(getTrace返回array类型，getTraceAsString返回string类型）。

__toString用以将异常对象字符串化，默认的实现能够打印出处异常代码外的其他所有字段。

\_\_clone被声明为private，表示Exception对象不能被复制。声明为final表示子类不能覆盖__clone()，从而使子类对象也不能被复制。尝试对 Exception 对象或其子类对象进行复制 会报错。

所有方法中，除了\_\_toString外都不能被子类覆盖。子类可覆盖__toString实现自定义格式的输出。

用法示例：
```
try{
	throw new Exception('msg1', 1, new Exception('msg2', 2));	
}catch (Exception $e){
	echo $e->getMessage() . "\n" .
		$e->getCode() . "\n" .
		$e->getFile() . "\n" .
		$e->getLine() . "\n" .
		$e->getTraceAsString() . "\n";
	var_dump($e->getTrace());
	echo $e->getPrevious();
	
	echo "\n";
	
	echo $e;
}

/*output:
msg1
1
/home/wK6nSp/prog.php
4
#0 {main}
array(0) {
}
exception 'Exception' with message 'msg2' in /home/wK6nSp/prog.php:4
Stack trace:
#0 {main}
exception 'Exception' with message 'msg2' in /home/wK6nSp/prog.php:4
Stack trace:
#0 {main}

Next exception 'Exception' with message 'msg1' in /home/wK6nSp/prog.php:4
Stack trace:
#0 {main}
*/
```

##用set_exception_handler()设置异常处理函数

set_exception_handler()用来设置一个用户自定义的异常处理函数，该函数在异常未被捕获时被执行，执行之后终止脚本。

如果没有设置异常处理函数，异常没有被捕获的默认处理方法是：PHP会Fatal Error，并且输出"Uncaught Exception ..."的信息。

函数原型：

```
callable set_exception_handler ( callable $exception_handler )
```

- 参数: 当一个未捕获的异常发生时所调用函数的名称。 该函数必须在调用 set_exception_handler() 之前已经定义。 该处理函数需要接受一个参数，该参数是一个抛出的异常对象。也可以传递一个 NULL 值用于重置异常处理函数为默认值。
- 返回值： 返回之前定义的异常处理程序的名称，或者在错误时返回 NULL。 如果之前没有定义一个错误处理程序，也会返回 NULL。 如果参数使用了 NULL，重置处理程序为默认状态，并且会返回 TRUE。

##内置的异常类型

内置的异常类型，最重要的是作为所有异常类的基类的Exception类。除此之外，PHP还在SPL库中定义了若干代表常见含义的异常类。这些类型只是简单地继承Exception而已，其唯一有意义的部分是它的名字。用来在特定的地方被抛出。比如InvalidArgumentException可用在参数类型和所需要参数类型不一致时被抛出（当然，也可用参数类型声明来约束参数类型）。例如：

```
function f($a){
	if (!is_int($a)){
		throw new InvalidArgumentException();
	}
	echo $a;
}

try{
	f(array(1));
}catch (Exception $e){
	echo $e;
}
/*output:
exception 'InvalidArgumentException' in /home/L68RIl/prog.php:5
Stack trace:
#0 /home/L68RIl/prog.php(11): f(Array)
#1 {main}
*/
```